services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    tty: true
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./init/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - main-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "${MONGO_INITDB__PORT}:27017"
    volumes:
      - ./data/mongodb_data:/data/db
      - ./init/mongo.js:/docker-entrypoint-initdb.d/mongo.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - main-network
    restart: unless-stopped

  hookwatch:
    build:
      context: ./hookwatch
      dockerfile: Dockerfile
    container_name: hookwatch
    restart: unless-stopped
    ports:
      - "${HOOKWATCH_PORT:-3000}:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017
      - REDIS_URI=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    networks:
      - main-network

  web-ui:
    image: nginx:alpine
    container_name: web-ui
    restart: unless-stopped
    ports:
      - "${WEB_UI_PORT:-8080}:80"
    volumes:
      - ./web:/usr/share/nginx/html
    networks:
      - main-network

networks:
  main-network:
    driver: bridge
