services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    tty: true
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./init/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - main-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "${MONGO_INITDB__PORT}:27017"
    volumes:
      - ./data/mongodb_data:/data/db
      - ./init/mongo.js:/docker-entrypoint-initdb.d/mongo.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - main-network
    restart: unless-stopped
